SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `workflow_step`;
DROP TABLE IF EXISTS `workflow_model_upload`;
DROP TABLE IF EXISTS `workflow`;
DROP TABLE IF EXISTS `standalone_validation`;
DROP TABLE IF EXISTS `model_asset`;
DROP TABLE IF EXISTS `dataset_asset`;
DROP TABLE IF EXISTS `sys_user`;

CREATE TABLE `dataset_asset` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `asset_code` varchar(64) NOT NULL,
  `asset_name` varchar(128) NOT NULL,
  `owner_user_id` bigint NOT NULL,
  `owner_role_code` varchar(32) NOT NULL,
  `dataset_type` varchar(64) NOT NULL DEFAULT 'IMAGE',
  `data_format` varchar(64) NOT NULL DEFAULT 'YOLO',
  `task_type` varchar(64) NOT NULL DEFAULT 'DETECTION',
  `sample_count` int DEFAULT NULL,
  `file_name` varchar(255) DEFAULT NULL,
  `file_path` varchar(500) DEFAULT NULL,
  `source_path` varchar(500) DEFAULT NULL,
  `source_type` varchar(32) NOT NULL DEFAULT 'LEGACY_PATH',
  `import_mode` varchar(32) NOT NULL DEFAULT 'LEGACY',
  `file_size` bigint DEFAULT NULL,
  `is_public` tinyint NOT NULL DEFAULT '0',
  `status` varchar(32) NOT NULL DEFAULT 'READY',
  `description` varchar(500) DEFAULT NULL,
  `is_deleted` tinyint NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `image_count` int NOT NULL DEFAULT '0',
  `file_path_validated` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dataset_asset_code` (`asset_code`),
  KEY `idx_dataset_asset_owner_user_id` (`owner_user_id`),
  KEY `idx_dataset_asset_owner_role_code` (`owner_role_code`),
  KEY `idx_dataset_asset_created_at` (`created_at`),
  KEY `idx_dataset_asset_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `model_asset` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `asset_code` varchar(64) NOT NULL,
  `asset_name` varchar(128) NOT NULL,
  `owner_user_id` bigint NOT NULL,
  `owner_role_code` varchar(32) NOT NULL,
  `model_type` varchar(64) NOT NULL DEFAULT 'YOLO',
  `model_version` varchar(64) NOT NULL DEFAULT 'YOLO10',
  `task_type` varchar(64) NOT NULL DEFAULT 'DETECTION',
  `file_name` varchar(255) DEFAULT NULL,
  `file_path` varchar(500) DEFAULT NULL,
  `source_path` varchar(500) DEFAULT NULL,
  `source_type` varchar(32) NOT NULL DEFAULT 'LEGACY_PATH',
  `import_mode` varchar(32) NOT NULL DEFAULT 'LEGACY',
  `file_size` bigint DEFAULT NULL,
  `is_public` tinyint NOT NULL DEFAULT '0',
  `status` varchar(32) NOT NULL DEFAULT 'READY',
  `description` varchar(500) DEFAULT NULL,
  `is_deleted` tinyint NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `file_path_validated` tinyint(1) NOT NULL DEFAULT '0',
  `yolo_version` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_model_asset_code` (`asset_code`),
  KEY `idx_model_asset_owner_user_id` (`owner_user_id`),
  KEY `idx_model_asset_owner_role_code` (`owner_role_code`),
  KEY `idx_model_asset_created_at` (`created_at`),
  KEY `idx_model_asset_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `standalone_validation` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `validation_code` varchar(64) NOT NULL,
  `user_id` bigint NOT NULL,
  `model_asset_id` bigint NOT NULL,
  `model_path` varchar(500) DEFAULT NULL,
  `dataset_asset_id` bigint NOT NULL,
  `dataset_path` varchar(500) DEFAULT NULL,
  `algorithm_type` varchar(64) NOT NULL DEFAULT 'YOLO',
  `status` varchar(32) NOT NULL DEFAULT 'PENDING',
  `progress` int NOT NULL DEFAULT '0',
  `python_job_id` varchar(64) DEFAULT NULL,
  `metrics_json` text,
  `result_file_path` varchar(500) DEFAULT NULL,
  `quality_label` varchar(32) DEFAULT NULL,
  `error_message` text,
  `finished_at` datetime DEFAULT NULL,
  `is_deleted` tinyint NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_standalone_validation_code` (`validation_code`),
  KEY `idx_sv_user_id` (`user_id`),
  KEY `idx_sv_model_asset_id` (`model_asset_id`),
  KEY `idx_sv_dataset_asset_id` (`dataset_asset_id`),
  KEY `idx_sv_status` (`status`),
  KEY `idx_sv_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sys_user` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `username` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
  `password_hash` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `display_name` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `email` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `role_code` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `status` varchar(20) COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'ACTIVE',
  `is_deleted` tinyint NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_user_username` (`username`),
  UNIQUE KEY `uk_sys_user_email` (`email`),
  KEY `idx_sys_user_role_code` (`role_code`),
  KEY `idx_sys_user_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `workflow` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `workflow_code` varchar(64) NOT NULL,
  `workflow_name` varchar(128) NOT NULL,
  `initiator_user_id` bigint NOT NULL,
  `server_user_id` bigint NOT NULL,
  `client_model_asset_id` bigint DEFAULT NULL,
  `server_dataset_asset_id` bigint DEFAULT NULL,
  `client_model_count` int NOT NULL DEFAULT '1',
  `is_public` tinyint NOT NULL DEFAULT '0',
  `status` varchar(32) NOT NULL,
  `current_step` varchar(255) DEFAULT NULL,
  `progress` int NOT NULL DEFAULT '0',
  `python_job_id` varchar(64) DEFAULT NULL,
  `remark` text,
  `metrics_json` text,
  `result_file_path` varchar(500) DEFAULT NULL,
  `result_retention_status` varchar(32) NOT NULL DEFAULT 'TEMPORARY',
  `result_saved_at` datetime DEFAULT NULL,
  `result_deleted_at` datetime DEFAULT NULL,
  `error_message` longtext,
  `is_deleted` tinyint NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `yolo_version` varchar(20) NOT NULL DEFAULT 'YOLOv10',
  `collected_model_count` int NOT NULL DEFAULT '0',
  `expected_model_count` int NOT NULL DEFAULT '1',
  `federated_status` varchar(32) NOT NULL DEFAULT 'PENDING',
  `federated_strategy` varchar(32) NOT NULL DEFAULT 'FEDML',
  `federated_model_asset_id` bigint DEFAULT NULL,
  `federated_started_at` datetime DEFAULT NULL,
  `federated_finished_at` datetime DEFAULT NULL,
  `dp_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `dp_epsilon` decimal(12,6) DEFAULT NULL,
  `dp_delta` decimal(18,12) DEFAULT NULL,
  `dp_clip_norm` decimal(12,6) DEFAULT NULL,
  `dp_noise_multiplier` decimal(12,6) DEFAULT NULL,
  `dp_status` varchar(32) NOT NULL DEFAULT 'DISABLED',
  `dp_summary` varchar(500) DEFAULT NULL,
  `shuffle_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `shuffle_batch_no` varchar(64) DEFAULT NULL,
  `shuffle_status` varchar(32) NOT NULL DEFAULT 'DISABLED',
  `shuffle_order_summary` varchar(500) DEFAULT NULL,
  `shuffle_started_at` datetime DEFAULT NULL,
  `shuffle_finished_at` datetime DEFAULT NULL,
  `secure_aggregation_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `secure_aggregation_mode` varchar(32) NOT NULL DEFAULT 'PLAIN',
  `secure_aggregation_status` varchar(32) NOT NULL DEFAULT 'DISABLED',
  `secure_aggregation_summary` varchar(500) DEFAULT NULL,
  `secure_aggregation_started_at` datetime DEFAULT NULL,
  `secure_aggregation_finished_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_workflow_code` (`workflow_code`),
  KEY `idx_workflow_initiator_user_id` (`initiator_user_id`),
  KEY `idx_workflow_server_user_id` (`server_user_id`),
  KEY `idx_workflow_status` (`status`),
  KEY `idx_workflow_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `workflow_model_upload` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `workflow_id` bigint NOT NULL,
  `uploader_id` bigint NOT NULL,
  `model_asset_id` bigint DEFAULT NULL,
  `server_model_asset_id` bigint DEFAULT NULL,
  `original_filename` varchar(255) NOT NULL,
  `stored_filename` varchar(255) DEFAULT NULL,
  `encrypted_file_path` varchar(500) DEFAULT NULL,
  `decrypted_file_path` varchar(500) DEFAULT NULL,
  `file_size` bigint DEFAULT NULL,
  `file_sha256` varchar(64) DEFAULT NULL,
  `aes_key_base64` varchar(512) DEFAULT NULL,
  `aes_iv_base64` varchar(100) DEFAULT NULL,
  `upload_token` varchar(64) DEFAULT NULL,
  `upload_status` varchar(20) NOT NULL DEFAULT 'PENDING',
  `error_message` longtext,
  `uploaded_at` datetime DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `token_expire_at` datetime DEFAULT NULL,
  `federated_round` int NOT NULL DEFAULT '1',
  `federated_weight` decimal(10,4) NOT NULL DEFAULT '1.0000',
  `aggregation_status` varchar(32) NOT NULL DEFAULT 'PENDING',
  `client_display_name` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_workflow_id` (`workflow_id`),
  KEY `idx_uploader_id` (`uploader_id`),
  KEY `idx_upload_token` (`upload_token`),
  KEY `idx_model_asset_id` (`model_asset_id`),
  KEY `idx_wmu_model_asset_id` (`model_asset_id`),
  KEY `idx_wmu_server_model_asset_id` (`server_model_asset_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `workflow_step` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `workflow_id` bigint NOT NULL,
  `step_no` int NOT NULL DEFAULT '1',
  `step_code` varchar(32) NOT NULL,
  `step_name` varchar(64) NOT NULL,
  `from_status` varchar(32) DEFAULT NULL,
  `to_status` varchar(32) NOT NULL,
  `operator_user_id` bigint DEFAULT NULL,
  `operator_role` varchar(32) DEFAULT NULL,
  `message` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_workflow_step_workflow_id` (`workflow_id`),
  KEY `idx_workflow_step_workflow_id_step_no` (`workflow_id`, `step_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;
