ALLOWED_TRANSITIONS = {
    "ACCEPTED": ["PREPARING", "VALIDATING"],
    "PREPARING": ["TRAINING_RUNNING"],
    "TRAINING_RUNNING": ["VALIDATING"],
    "VALIDATING": ["VALIDATING", "COMPLETED", "FAILED"]
}
